[新機能]: ステージの登録機能を追加
koryuServer/SkillMaster pull request #290
Opened 2023-01-20 13:50 UTC by Koryu25

### 具体的な実装方法または変更点
- ステージを登録できるようにした
- 登録したステージにゲームタイプごとの情報(フィールド)を登録できるようにした
- ステージをコピーできるようにした
- ステージとフィールドの削除コマンドを追加した

### テストして頂きたいこと
- [ ]  ステージが登録できるか
- [ ] フィールドを登録できるか
- [ ] ステージをコピーできるか
- [ ] フィールドを削除できるか
- [ ] ステージを削除できるか

テスト方法については[こちら](https://github.com/koryuServer/SkillMaster/issues/250)を参照してください

### 関連するIssue
- close #250

2023-01-20 14:22 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +import com.github.syari.spigot.api.item.displayName
インポートは辞書順に並べ、間に空白行を入れないこと。

2023-01-20 15:47 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +import com.github.syari.spigot.api.item.displayName
辞書順とは…

2023-01-20 16:22 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +import com.github.syari.spigot.api.item.displayName
import順がアルファベット順じゃないからエラーになっているのでは？
たぶん、`import kotlin.properties.Delegates`が`import com.github.syari.spigot.api.item.displayName`の次にくれば解決すると思われる

2023-01-21 13:54 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
`originLocation`はどこで初期化されるんですか？

2023-01-21 13:54 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +        }
```kotlin
originBlock = ItemStack(Material.OBSIDIAN).apply {
 displayName = "" ....
}
```
みたいな形で書いたほうが良いと思います

2023-01-21 13:54 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/GameType.kt
> +enum class GameType(
`numberOfPlayer`は指定するENUMの値によって値が変わるので、`enum class`として定数の役割を果たしていないのではないでしょうか。
したがって、`sealed class`を使ったほうがいいと思います

2023-01-21 13:54 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +    lateinit var origin: Location
`origin`はどこで初期化されていますか？

2023-01-21 13:54 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        get() = otherLocs.size >= gameType.numberOfOtherLoc
`get() = `ってなんか、Kotlinのいいところ削ぎ落している気がします

2023-01-21 14:02 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
コメントで明記したほうがいいですか？

2023-01-21 14:04 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
`lateinit`を付けていた場合、原則クラス内で初期化していてほしいです。
もしそうでない場合は、プロパティをコンストラクタに指定したほうがいいと思います

2023-01-21 14:06 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/GameType.kt
> +enum class GameType(
定数の役割とはなんですか？

2023-01-21 14:07 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        get() = otherLocs.size >= gameType.numberOfOtherLoc
Kotlinのいいところとそれをそぎ落としてはいけない理由はなんですか？

2023-01-21 14:10 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
このoriginLocationは特定のブロックを設置したときに定義されます。（EventListener）
えるどさんならえるどさんの意見をどういう方法で適応させますか？

2023-01-21 14:11 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +        }
apply便利ですね。OKです。そうします

2023-01-21 14:19 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        get() = otherLocs.size >= gameType.numberOfOtherLoc
個人的な意見としては、`Kotlinのいいところを削ぎ落とす=>Kotlinの公式ドキュメントに従っていない`ので、一般的なコードではなくなります。一般的なコードでないということは、それだけで`読みづらいコード`となり、保守性が下がります。

あと、`get()='は[関心の分離の原則](https://ja.wikipedia.org/wiki/%E9%96%A2%E5%BF%83%E3%81%AE%E5%88%86%E9%9B%A2)にも従っていないので良くない、という観点もありますね。
関心の分離の原則は、従うことによってカプセル化の実装のしやすさや、機能実装のしやすさが向上します。
要は「クラスの中で関心ごとは定めたほうが、設計上シンプルになりシステム自体の保守・運用がしやすくなるよね」みたいな話です。

2023-01-21 14:21 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        get() = otherLocs.size >= gameType.numberOfOtherLoc
Kotlinのいいところについては、簡単に言うと簡潔に書けることですね。

簡単に書けることによって、だれもが見やすいコードを書けて流派が少なくなります。
それによって、みんなが読みやすいコードをかけて保守性が上がります。

2023-01-21 14:27 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/GameType.kt
> +enum class GameType(
そもそも`enum class`は変動しない値（定数）を定義するためのclassです。
よって、`enum class`に変動する値があるのは`enum class`の持つ役割として役割を持ちすぎだと思います。（そう書けてしまうKotlinが悪いと言ってしまえばそれまでですが・・・）

これは、例えば中華鍋でパスタ作っているようなものですね。
中華鍋ではパスタも作れますが、それでは中華鍋が持っている役割を超えてますし、普通の鍋使ったほうが扱いやすいですよね。

結論として、`enum class`が果たすべきなのは定数の定義であって、そこに変数の処理は加えるのはよくないと思います

2023-01-21 14:28 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
それなら
```kotlin
var originLocation = Location(null, 0,0,0)
```
でいいんじゃないでしょうか

2023-01-22 03:30 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +                }
これなら
```kotlin
val originBlock: ItemStack = ItemStack(Material.OBSIDIAN).apply {
                displayName = "[$stageName]原点ブロック"
                editMeta { meta ->
                    meta.lore = listOf(
                        "このブロックでステージの原点を指定します",
                        "登録中のステージ: $stageName"
                    )
                    meta.addEnchant(Enchantment.DURABILITY, 1, false)
                    meta.addItemFlags(ItemFlag.HIDE_ENCHANTS)
                }
```
のほうがシンプルですし、可読性あがるのではいいのでは？

2023-01-22 03:48 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    lateinit var originLocation: Location
OKです。やります

2023-01-22 03:57 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/GameType.kt
> +enum class GameType(
OKです。GameType改変します。

2023-01-22 04:42 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        get() = otherLocs.size >= gameType.numberOfOtherLoc
OKです。関数にします。

2023-01-22 15:19 UTC, Koryu25 commented
一通りレビューを適応させました

2023-01-23 02:51 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    class StageCopyerList {
この`~~List`クラスが増えてしまう現象は、スケーラビリティが低く、クラス構造も複雑になってしまうので避けたほうがいいですね。

以下の２つの手法を取れば改善できそうですね。
1. `~List`をまとめるAPIクラス（SkillMasterAPI）みたいなものを作る
2. Listのextension（拡張関数）として、`hasPlayer(player: Player)`や`get(player: Player)`、`remove(player: Player)`を加える。

2023-01-23 02:51 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
get() {} 使わなくていいと思います

2023-01-23 02:51 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
get{} 使わなくていいと思います

2023-01-23 03:01 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    class StageCopyerList {
正確に書けているかはわからんけど、2番はこんな感じ
```kotlin
fun <T: Listable> List<T>.hasPlayer(player: Player): Boolean {
    for (obj in this) {
        if (obj.player == player) return true
    }
    return false
}

fun <T: Listable> List<T>.getByPlayer(player: Player): T {
    for (obj in this) {
    	if (obj.player == player) return copyer
    }
   	throw IllegalArgumentException("Not found Listable instance has Player[${player.name}]")
}

fun <T: Listable> List<T>.remove(player: Player) {
    if (!this.hasPlayer(player)) return
    val obj = this.getByPlayer(player)

    remove(obj)
}
```

2023-01-23 06:42 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
[理由](https://discord.com/channels/797765988300750869/987989072020668416/1066969978626117662)

2023-01-23 06:42 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
[理由](https://discord.com/channels/797765988300750869/987989072020668416/1066969978626117662)

2023-01-23 11:12 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCopyer.kt
> +    class StageCopyerList {
あとで実装しましょう

2023-01-23 11:16 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
なおします

2023-01-23 11:16 UTC, Koryu25 commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/StageCreator.kt
> +        }
なおします

2023-01-27 14:32 UTC, Koryu25 commented
@hirotask レビューお願い

2023-01-28 03:04 UTC, hirotask requested changes

2023-01-28 03:04 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        }
ここも`apply`使えば楽に欠けるので修正お願いします

2023-01-28 03:04 UTC, hirotask commented on src/main/java/net/lifecity/mc/skillmaster/game/stage/field/FieldCreator.kt
> +        }
上に同じ

2023-01-28 03:24 UTC, hirotask approved these changes
![LGTM](https://images.lgtmgen.org/090a5a7e-f40a-4045-b07d-344c64bd8fd2)

2023-01-28 03:29 UTC, hirotask commented
Actionsが動かないのは、おそらくこのActions作成者のミス（[たぶんこのDockerfile](https://github.com/ScaCap/action-ktlint/blob/master/Dockerfile)が原因）だと思うのでマージしちゃって大丈夫です。

2023-01-28 04:34 UTC, merged